database/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(80), nullable=False)
    role = db.Column(
        db.Enum("Admin", "User", "Manager", "Analyst"),
        nullable=False,
        default="User"
        )
    group_id = db.Column(db.Integer, db.ForeignKey("group.id"))

    def is_admin(self):
        return self.role == "Admin"
    
    def is_manager(self):
        return self.role == "Manager"
    
    def is_analyst(self):
        return self.role == "Analyst"



class Group(db.Model):
    id  = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    users = db.relationship("User", backref="group")


class Ticket(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    note = db.Column(db.Text, nullable=False)
    status = db.Column(
        db.Enum("Pending", "Closed", "In review"), default="Pending", nullable=False
        )
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    group_id = db.Column(db.Integer, db.ForeignKey("group.id"))

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField, SelectField, ValidationError
from wtforms.validators import DataRequired, EqualTo, Length


from database.models import User


class RegisterForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=3, max=20)])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=3, max=20)])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(), EqualTo("password")])
    submit = SubmitField("Register")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError("Please use a different username.")

class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")


class TicketForm(FlaskForm):
    note = TextAreaField("Note", validators=[DataRequired()])
    status = SelectField(
        "Status", 
        choices=[("Pending", "Pending"), ("Closed", "Closed"), ("In review", "In review")],
        default="Pending",
        validators=[DataRequired()]
        )
    submit = SubmitField("Create ticket")


class DeleteTicketForm(FlaskForm):
    submit = SubmitField("Delete")

app.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from database.models import db, migrate, User, Group
from werkzeug.security import generate_password_hash, check_password_hash
import routes

from config import ADMIN_PASSWORD



app = Flask(__name__)
app.config.from_object("config")
db.init_app(app)
migrate.init_app(app, db)
app.register_blueprint(routes.main_bp)
login_manager = LoginManager(app)
login_manager.login_view = "login"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@app.before_request
def create_tables():
    db.create_all()
    if not User.query.first():
        user = User(
            username="admin",
            password=generate_password_hash(ADMIN_PASSWORD, method="pbkdf2:sha256"),
            role="Admin"
            )
        customer1 = Group(name="Customer 1")
        customer2 = Group(name="Customer 2")
        customer3 = Group(name="Customer 3")
        db.session.add_all([user, customer1, customer2, customer3])
        db.session.commit()

    


if __name__ == "__main__":
    app.run(debug=True)

routes.py
from flask import Blueprint, abort, flash, request
from flask import render_template, redirect, url_for
from flask_login import login_required, login_user, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash

from forms import LoginForm, RegisterForm, TicketForm, DeleteTicketForm
from database.models import User, db, Group, Ticket
from decorators import admin_required, admin_or_manager_required, analyst_required


main_bp = Blueprint("main", __name__, template_folder="templates")



@main_bp.route("/")
def index():
    return render_template("index.html")


@main_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            flash("Login success!", category="success")
            return redirect(url_for("main.index"))
    return render_template("login.html", form=form)


@main_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data, method="pbkdf2:sha256"),
            role="User",
        )
        db.session.add(user)
        db.session.commit()
        flash("Account created!", category="success")
        return redirect(url_for("main.login"))
    return render_template("register.html", form=form)


@main_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.login"))


@main_bp.route("/tickets")
@login_required
def tickets():
    form = DeleteTicketForm()
    if current_user.is_admin():
        tickets = Ticket.query.all()
    else:
        tickets = Ticket.query.filter_by(user_id=current_user.id)
    return render_template("tickets.html", tickets=tickets, form=form)


@main_bp.route("/tickets/new", methods=["GET", "POST"])
@login_required
@admin_or_manager_required
def create_ticket():
    form = TicketForm()
    if form.validate_on_submit():
        ticket = Ticket(
            note=form.note.data,
            status="Pending",
            user_id=current_user.id,
        )
        db.session.add(ticket)
        db.session.commit()
        flash("Ticket created!", category="success")
        return redirect(url_for("main.tickets"))
    return render_template("create_ticket.html", form=form)


@main_bp.route("/tickets/<int:ticket_id>/update", methods=["GET", "POST"])
@login_required
@admin_or_manager_required
def update_ticket(ticket_id):
    ticket = Ticket.query.get_or_404(ticket_id)
    form = TicketForm()
    if form.validate_on_submit():
        ticket.note = form.note.data
        ticket.status = form.status.data
        db.session.commit()
        flash("Ticket updated!", category="success")
        return redirect(url_for("main.tickets"))
    elif request.method == 'GET':
        form.note.data = ticket.note
        form.status.data = ticket.status
    return render_template('create_ticket.html', form=form)


@main_bp.route("/tickets/<int:ticket_id>/delete", methods=["POST"])
@login_required
@admin_required
def delete_ticket(ticket_id):
    ticket = Ticket.query.get_or_404(ticket_id)
    form = DeleteTicketForm()
    if form.validate_on_submit():
        db.session.delete(ticket)
        db.session.commit()
        flash("Ticket deleted!", category="success")
    return redirect(url_for("main.tickets"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock%}
</head>
<body>
    {% block navbar %}{% endblock %}
    {% block content %}{% endblock %}
</body>
</html>

templates/create_ticket.html
{% extends "base.html"%}

{% block title %}<title>Update Ticket</title>{% endblock %}

{% block content %}
<h1>Update Ticket</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <p>
        {{ form.note }}<br>
        {{ form.status }}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}<title>Main page</title>{% endblock %}

{% block navbar %}
<nav>
    <ul>
        <li><a href="{{ url_for('main.index') }}">Home</a></li>
        <li><a href="{{ url_for('main.tickets') }}">Tickets</a></li>
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for("main.logout") }}">Logout</a></li>
        {% else %}
        <li><a href="{{ url_for("main.register") }}">Register</a></li>
        <li><a href="{{ url_for("main.login") }}">Login</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock%}

{% block content %}
<h1>Wellcome, {{ current_user.username if current_user.username else "Guest"}}</h1>
{% endblock %}

templates/register.html
{% extends "base.html"%}

{% block title %}<title>Register</title>{% endblock %}

{% block content %}
<h1>Register</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}<br>
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
    </p>
    <p>
        {{ form.confirm_password.label }}<br>
        {{ form.confirm_password(size=32) }}<br>
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock%}

templates/tickets.html
{% extends "base.html" %}

{% block title %}<title>Tickets</title>{% endblock %}

{% block content %}
<h2>Existing Tickets</h2>
<ul>
    {% for ticket in tickets %}
    <li>
        <strong>Status:</strong> {{ ticket.status }}<br>
        <strong>Note:</strong> {{ ticket.note }}<br>
        <strong>Group ID:</strong> {{ ticket.group_id }}<br>
        <strong>User ID:</strong> {{ ticket.user_id }}
    </li>
    <br>
    {% if ticket%}
        {% if current_user.is_admin() or current_user.is_manager() %}
            <a class="btn btn-primary" href="{{ url_for('main.update_ticket', ticket_id=ticket.id) }}">Update Ticket</a>

            {% if current_user.is_admin() %}
            <form action="{{ url_for('main.delete_ticket', ticket_id=ticket.id) }}" method="POST">
                {{ form.hidden_tag() }}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            {% endif %}
        {% endif %}
    {% endif %}
    {% endfor %}
</ul>

{% if current_user.is_authenticated %}
    {% if current_user.is_admin() or current_user.is_manager() %}
        <a href="{{ url_for('main.create_ticket') }}">Create Ticket</a>
    {% endif %}
{% endif%}
{% endblock %}